apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cicd
  template:
    metadata:
      labels:
        app: cicd
    spec:
      containers:
      - name: cicd
        image: soumyadeep90014842/cicd-app:38
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "500M"
            cpu: "125m"
          limits:
            memory: "500M"
            cpu: "125m"
